---
- name: Generate BGP Reflector Configuration
  junos_config:
    lines: "{{ lookup('template', 'bgp_reflector.j2').split('\n') }}"
    comment: "Configured BGP"
  when: bgp_reflector == True

- name: Generate BGP Client Configuration
  junos_config:
    lines: "{{ lookup('template', 'bgp_client.j2').split('\n') }}"
    comment: "Configured BGP"
  when: bgp_reflector == False
