---
- name: Generate BGP Configuration
  junos_config:
    lines: "{{ lookup('template', 'bgp_config.j2').split('\n') }}"
    comment: "Configured BGP"
  when: bgp_remove == False

- name: Remove BGP Configuration
  junos_config:
    lines: "{{ lookup('template', 'bgp_remove.j2').split('\n') }}"
    comment: "Configured BGP"
  when: bgp_remove == True

